# Generated by Django 5.2.3 on 2025-06-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tareas',
            new_name='Tarea',
        ),
    ]
