# Generated by Django 5.2.3 on 2025-06-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_rename_tareas_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='categoria',
            field=models.CharField(choices=[('Universidad', 'Universidad'), ('Personal', 'Personal'), ('Trabajo', 'Trabajo')], default='Personal', max_length=100),
        ),
    ]
